# Example Docker Compose configuration for Vite development
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      # Vite configuration for WordPress
      VITE_SERVER_HOST: node
      VITE_HMR_HOST: localhost
      VITE_HMR_CLIENT_PORT: 3000
      VITE_DEV_SERVER_ENABLED: 'true'
      WP_DEBUG: 'true'
      WP_ENVIRONMENT_TYPE: development
    volumes:
      - ./:/var/www/html/wp-content/plugins/my-plugin
      - wordpress_data:/var/www/html
    depends_on:
      - db
      - node
    networks:
      - wp_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network

  node:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      # Vite server configuration
      VITE_SERVER_HOST: 0.0.0.0
      VITE_SERVER_PORT: 3000
      VITE_HMR_HOST: localhost
      VITE_HMR_PORT: 3000
      # Development mode
      NODE_ENV: development
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: >
      sh -c "npm install && npm run dev"
    networks:
      - wp_network

  # Optional: PHPMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - wp_network

volumes:
  wordpress_data:
  db_data:
  node_modules:

networks:
  wp_network:
    driver: bridge