name: Release

on:
  push:
    branches:
      - main
      - 'support/*'

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write
  checks: write
  repository-projects: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          # Use a personal access token or GitHub App token with bypass permissions
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN || secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v5
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/changelog@latest
            @semantic-release/git@latest
            conventional-changelog-conventionalcommits@latest
        env:
          # Use the token with bypass permissions
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN || secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com

      # Packagist update is automatic if GitHub app is configured
      # Uncomment the following step only if manual trigger is needed
      # - name: Trigger Packagist update
      #   if: steps.semantic.outputs.new_release_published == 'true'
      #   run: |
      #     curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}' -d'{"repository":{"url":"https://packagist.org/packages/wp-spaghetti/wp-vite"}}'
